version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: n-test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
